name: go_test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
    test:
        name: go_test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/setup-go@v3
          with:
            go-version: ^1.20
        - uses: actions/checkout@v3
        - name: go test
          run: go test ./...
